apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: go-grpc-template
data:
  APP_NAME: gateway
  GO_ENV: production
  GATEWAY_PORT: "8080"
  GATEWAY_METRICS_PORT: "9090"
  USER_GRPC_HOST: user
  USER_GRPC_PORT: "50051"
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
  OTEL_SERVICE_NAME: gateway
  LOG_LEVEL: info
  CORS_ALLOW_ORIGINS: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: go-grpc-template
data:
  APP_NAME: user-service
  GO_ENV: production
  USER_GRPC_PORT: "50051"
  USER_METRICS_PORT: "9091"
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
  OTEL_SERVICE_NAME: user-service
  LOG_LEVEL: info
