apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-grpc-template

resources:
  - namespace.yaml
  - configmap.yaml
  - gateway.yaml
  - user.yaml

commonLabels:
  app.kubernetes.io/part-of: go-grpc-microservice-template
  app.kubernetes.io/managed-by: kustomize
