services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./deploy/monitoring/otel-collector.yml:/etc/otel-collector.yml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./deploy/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9099:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
